from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from datetime import datetime, date
from typing import Optional
import json
import sxtwl

from app.bazi import calculate_bazi, enrich_with_localized_pillars, analyze_three_pillars
from app.mbti import get_mbti_profile, get_mbti_bazi_combined_context
from app.llm import complete
from app.prompts import (
    profile_summary_prompt,
    daily_guidance_prompt,
    chat_prompt,
    contains_crisis_language,
    get_crisis_response,
)

GAN = ["Jia","Yi","Bing","Ding","Wu","Ji","Geng","Xin","Ren","Gui"]
ZHI = ["Zi","Chou","Yin","Mao","Chen","Si","Wu","Wei","Shen","You","Xu","Hai"]

app = FastAPI(title="oria-analysis-service")

class BaziRequest(BaseModel):
    year: int
    month: int
    day: int
    hour: int = 0
    minute: int = 0
    tz_name: str = "Asia/Hong_Kong"
    location: Optional[str] = None
    time_known: Optional[bool] = None
    lang: str = "en"

class MbtiRequest(BaseModel):
    mbti_type: str
    lang: str = "en"

class ProfileSummaryRequest(BaseModel):
    mbti_type: str
    day_master: str
    dominant_element: str
    lang: str = "en"

class ProfileSummaryAIRequest(BaseModel):
    bazi: dict
    mbti_type: str
    lang: str = "en"

class DailyGuidanceRequest(BaseModel):
    bazi: dict
    target_date: Optional[str] = None
    lang: str = "en"

class ChatRequest(BaseModel):
    bazi: dict
    mbti_type: str
    history: list = []
    user_message: str
    summary: str = ""
    lang: str = "en"

@app.get("/health")
def health():
    return {"status": "ok", "service": "oria-analysis-service"}

@app.post("/bazi/calculate")
def bazi_calculate(req: BaziRequest):
    try:
        birth_dt = datetime(req.year, req.month, req.day, req.hour, req.minute)
        result = calculate_bazi(
            birth_date=birth_dt,
            tz_name=req.tz_name,
            location=req.location,
            time_known=req.time_known,
        )
        enrich_with_localized_pillars(result, lang=req.lang)
        analysis = analyze_three_pillars(result, lang=req.lang)
        return {"bazi": result, "analysis": analysis}
    except Exception as e:
        raise HTTPException(status_code=400, detail=str(e))

@app.post("/mbti/profile")
def mbti_profile(req: MbtiRequest):
    try:
        return get_mbti_profile(req.mbti_type, req.lang)
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))

@app.post("/profile/combined-context")
def combined_context(req: ProfileSummaryRequest):
    try:
        context = get_mbti_bazi_combined_context(
            mbti_type=req.mbti_type,
            day_master=req.day_master,
            dominant_element=req.dominant_element,
            lang=req.lang,
        )
        return {"context": context}
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))

@app.post("/profile/summary")
def profile_summary(req: ProfileSummaryAIRequest):
    try:
        mbti = get_mbti_profile(req.mbti_type, req.lang)
        messages = profile_summary_prompt(req.bazi, mbti, req.lang)
        raw = complete(messages)
        clean = raw.strip().removeprefix("```json").removeprefix("```").removesuffix("```").strip()
        return json.loads(clean)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/daily-guidance/generate")
def daily_guidance_generate(req: DailyGuidanceRequest):
    try:
        target = date.fromisoformat(req.target_date) if req.target_date else date.today()
        lunar = sxtwl.fromSolar(target.year, target.month, target.day)
        day_gz = lunar.getDayGZ()
        today_stem = GAN[day_gz.tg]
        today_branch = ZHI[day_gz.dz]
        messages = daily_guidance_prompt(req.bazi, today_stem, today_branch, req.lang)
        raw = complete(messages)
        clean = raw.strip().removeprefix("```json").removeprefix("```").removesuffix("```").strip()
        return json.loads(clean)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/chat")
def chat(req: ChatRequest):
    try:
        # crisis check first — before anything else
        if contains_crisis_language(req.user_message):
            return {
                "response": get_crisis_response(req.lang),
                "crisis_detected": True,         # local filter caught it
                "safety_note": "Crisis keywords detected before LLM call."
            }

        mbti = get_mbti_profile(req.mbti_type, req.lang)
        messages = chat_prompt(
            bazi=req.bazi,
            mbti=mbti,
            history=req.history,
            user_message=req.user_message,
            summary=req.summary,
            lang=req.lang,
        )
        response = complete(messages)
        return {
            "response": response,
            "crisis_detected": False,
            "safety_note": "Response generated by LLM with safety instructions applied."
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
